# SPDX-FileCopyrightText: 2024 Simon Dalvai <info@simondalvai.org>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "99 Managers Futsal Edition"
SPDX-PackageSupplier = "Simon Dalvai <info@simondalvai.org>"
SPDX-PackageDownloadLocation = "https://codeberg.org/dulvui/99managers-futsal-edition"

[[annotations]]
path = [
    "game/**.tscn",
    "game/**.uid",
    "game/**.tres",
    "game/project.godot",
    "**.import",
    "game/export_presets.**",
    "game/themes/**",
    "scripts/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Simon Dalvai <info@simondalvai.org>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

# Translations with Weblate https://hosted.weblate.org/projects/99-managers-futsal-edition/game/
[[annotations]]
path = [
    "game/translations/**",
    "translations/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Simon Dalvai <info@simondalvai.org> and contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
    "game/icon.png",
    "game/icon_dark.png",
    "game/assets/player/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Simon Dalvai <info@simondalvai.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
    ".gitignore",
    "scripts/.gitignore",
    "version",
    "game/default_profile.build",
    "game/export_credentials.android.example",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Simon Dalvai <info@simondalvai.org>"
SPDX-License-Identifier = "CC0-1.0"

######################
# THIRD PARTY ASSETS AND DATA
#####################

# city names taken from Wikipedia
[[annotations]]
path = [
    "game/data/world/world.csv",
    "game/data/world/test_world.csv",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Wikipedia"
SPDX-License-Identifier = "CC-BY-SA-4.0"

# city names taken from Wikipedia
[[annotations]]
path = [
    "game/data/player_names/**.json",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2012 Daniele Faraglia"
SPDX-License-Identifier = "MIT"

# https://publicdomainvectors.org/
# modified color to white
[[annotations]]
path = [
    "game/assets/player_silhouettes/silhouette-football-04.svg",
    "game/assets/player_silhouettes/silhouette-football-08.svg",
    "game/assets/player_silhouettes/silhouette-football-10.svg",
    "game/assets/player_silhouettes/silhouette-football-11.svg",
    "game/assets/player_silhouettes/silhouette-football-12.svg",
    "game/assets/player_silhouettes/silhouette-football-15.svg",
    "game/assets/player_silhouettes/silhouette-football-16.svg",
    "game/assets/player_silhouettes/silhouette-football-18.svg",
    "game/assets/player_silhouettes/silhouette-football-19.svg",
    "game/assets/player_silhouettes/silhouette-football-20.svg",
    "game/assets/player_silhouettes/silhouette-football-22.svg",
    "game/assets/player_silhouettes/silhouette-football-24.svg",
    "game/assets/player_silhouettes/silhouette-football-25.svg",
    "game/assets/player_silhouettes/silhouette-football-26.svg",
    "game/assets/player_silhouettes/silhouette-football-28.svg",
    "game/assets/player_silhouettes/silhouette-football-32.svg",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# https://openclipart.org/detail/167872/soccerball-noshadow
[[annotations]]
path = [
    "game/assets/ball.svg",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2012 Ross Duris"
SPDX-License-Identifier = "CC0-1.0"

# https://game-icons.net/1x1/delapouite/round-star.html
[[annotations]]
path = [
    "game/assets/round-star.png",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) Delapouite"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = [
    "game/assets/audio/switch_001.ogg",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2020 Kenney (kenney.nl)"
SPDX-License-Identifier = "CC0-1.0"

# joypad button glyphs font https://shinmera.com/promptfont
[[annotations]]
path = [
    "game/assets/fonts/promptfont.ttf",
    "game/assets/joypad_glyphs/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) Yukari 'Shinmera' Hafner"
SPDX-License-Identifier = "OFL-1.1"

# Inter font https://rsms.me/inter/
[[annotations]]
path = [
    "game/assets/fonts/inter/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2020 The Inter Project Authors (https://github.com/rsms/inter)"
SPDX-License-Identifier = "OFL-1.1"

# https://openclipart.org/detail/222076/white-mouse-cursor-arrow
[[annotations]]
path = [
    "game/assets/mouse-cursor.svg",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) qubodupt"
SPDX-License-Identifier = "CC0-1.0"
