# SPDX-FileCopyrightText: 2024 Simon Dalvai <info@simondalvai.org>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Futsal Manager"
SPDX-PackageSupplier = "Simon Dalvai <info@simondalvai.org>"
SPDX-PackageDownloadLocation = "https://github.com/dulvui/futsal-manager"

[[annotations]]
path = [
    "game/**.tscn",
    "game/**.tres",
    "game/project.godot",
    "**.import",
    "game/export_presets.**",
    "game/themes/**",
    "game/translations/translations.csv",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Simon Dalvai <info@simondalvai.org>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
    "game/icon.png",
    "game/icon_dark.png",
    "game/assets/body.png",
    "game/assets/head.png",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Simon Dalvai <info@simondalvai.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
    ".gitignore",
    "version",
    "game/default_profile.build",
    "game/export_credentials.android.example",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Simon Dalvai <info@simondalvai.org>"
SPDX-License-Identifier = "CC0-1.0"

######################
# THIRD PARTY ASSETS AND DATA
#####################

# city names taken from Wikipedia
[[annotations]]
path = [
    "game/data/world/world.csv",
    "game/data/world/test_world.csv",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Wikipedia"
SPDX-License-Identifier = "CC-BY-SA-4.0"

# city names taken from Wikipedia
[[annotations]]
path = [
    "game/data/player_names/**.json",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2012 Daniele Faraglia"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "game/assets/ball.svg",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2012 Ross Duris"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "game/assets/audio/switch_001.ogg",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2020 Kenney (kenney.nl)"
SPDX-License-Identifier = "CC0-1.0"

# joypad button glyphs font https://shinmera.com/promptfont
[[annotations]]
path = [
    "game/assets/fonts/promptfont.ttf",
    "game/assets/joypad_glyphs/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) Yukari 'Shinmera' Hafner"
SPDX-License-Identifier = "OFL-1.1"

# Roboto font https://fonts.google.com/specimen/Roboto
[[annotations]]
path = [
    "game/assets/fonts/roboto/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2011 Google Inc."
SPDX-License-Identifier = "Apache-2.0"

# https://openclipart.org/detail/222076/white-mouse-cursor-arrow
[[annotations]]
path = [
    "game/assets/mouse-cursor.svg",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) qubodupt"
SPDX-License-Identifier = "CC0-1.0"
