# SPDX-FileCopyrightText: 2023 Simon Dalvai <info@simondalvai.org>

# SPDX-License-Identifier: AGPL-3.0-or-later

#
# Kind of a hack to get Godot detect continent and nation names
# so they get added to game.pot file for translations
#

class_name NationNames

# europe
var albania: String = tr("Albania")
var andorra: String = tr("Andorra")
var armenia: String = tr("Armenia")
var austria: String = tr("Austria")
var azerbaijan: String = tr("Azerbaijan")
var belarus: String = tr("Belarus")
var belgium: String = tr("Belgium")
var bosnia_and_herzegovina: String = tr("Bosnia and Herzegovina")
var bulgaria: String = tr("Bulgaria")
var croatia: String = tr("Croatia")
var cyprus: String = tr("Cyprus")
var czech_republic: String = tr("Czech Republic")
var denmark: String = tr("Denmark")
var estonia: String = tr("Estonia")
var finland: String = tr("Finland")
var france: String = tr("France")
var georgia: String = tr("Georgia")
var germany: String = tr("Germany")
var greece: String = tr("Greece")
var hungary: String = tr("Hungary")
var iceland: String = tr("Iceland")
var ireland: String = tr("Ireland")
var italy: String = tr("Italy")
var latvia: String = tr("Latvia")
var liechtenstein: String = tr("Liechtenstein")
var lithuania: String = tr("Lithuania")
var luxembourg: String = tr("Luxembourg")
var macedonia: String = tr("Macedonia")
var malta: String = tr("Malta")
var moldova: String = tr("Moldova")
var monaco: String = tr("Monaco")
var montenegro: String = tr("Montenegro")
var netherlands: String = tr("Netherlands")
var norway: String = tr("Norway")
var poland: String = tr("Poland")
var portugal: String = tr("Portugal")
var romania: String = tr("Romania")
var san_marino: String = tr("San Marino")
var serbia: String = tr("Serbia")
var slovakia: String = tr("Slovakia")
var slovenia: String = tr("Slovenia")
var spain: String = tr("Spain")
var sweden: String = tr("Sweden")
var switzerland: String = tr("Switzerland")
var ukraine: String = tr("Ukraine")
var united_kingdom: String = tr("United Kingdom")
var vatican_city: String = tr("Vatican City")

# south america
var brazil: String = tr("Brazil")
var argentina: String = tr("Argentina")
var bolivia: String = tr("Bolivia")
var chile: String = tr("Chile")
var colombia: String = tr("Colombia")
var ecuador: String = tr("Ecuador")
var guyana: String = tr("Guyana")
var paraguay: String = tr("Paraguay")
var peru: String = tr("Peru")
var suriname: String = tr("Suriname")
var uruguay: String = tr("Uruguay")
var venezuela: String = tr("Venezuela")

# north america
var antigua_and_barbuda: String = tr("Antigua and Barbuda")
var bahamas: String = tr("Bahamas")
var barbados: String = tr("Barbados")
var belize: String = tr("Belize")
var canada: String = tr("Canada")
var costa_rica: String = tr("Costa Rica")
var cuba: String = tr("Cuba")
var dominica: String = tr("Dominica")
var dominican_republic: String = tr("Dominican Republic")
var el_salvador: String = tr("El Salvador")
var grenada: String = tr("Grenada")
var guatemala: String = tr("Guatemala")
var haiti: String = tr("Haiti")
var honduras: String = tr("Honduras")
var jamaica: String = tr("Jamaica")
var mexico: String = tr("Mexico")
var nicaragua: String = tr("Nicaragua")
var panama: String = tr("Panama")
var saint_kitts_and_nevis: String = tr("Saint Kitts and Nevis")
var saint_lucia: String = tr("Saint Lucia")
var saint_vincent_and_the_grenadines: String = tr("Saint Vincent and the Grenadines")
var trinidad_and_tobago: String = tr("Trinidad and Tobago")
var usa: String = tr("Usa")

# oceania
var australia: String = tr("Australia")
var fiji: String = tr("Fiji")
var kiribati: String = tr("Kiribati")
var marshall_islands: String = tr("Marshall Islands")
var micronesia: String = tr("Micronesia")
var nauru: String = tr("Nauru")
var new_zealand: String = tr("New Zealand")
var palau: String = tr("Palau")
var papua_new_guinea: String = tr("Papua New Guinea")
var samoa: String = tr("Samoa")
var solomon_islands: String = tr("Solomon Islands")
var tonga: String = tr("Tonga")
var tuvalu: String = tr("Tuvalu")
var vanuatu: String = tr("Vanuatu")

# africa
var algeria: String = tr("Algeria")
var angola: String = tr("Angola")
var benin: String = tr("Benin")
var botswana: String = tr("Botswana")
var burkina: String = tr("Burkina")
var burundi: String = tr("Burundi")
var cameroon: String = tr("Cameroon")
var cape_verde: String = tr("Cape Verde")
var central_african_republic: String = tr("Central African Republic")
var chad: String = tr("Chad")
var comoros: String = tr("Comoros")
var congo: String = tr("Congo")
var democratic_republic_of_congo: String = tr("Democratic Republic of Congo")
var djibouti: String = tr("Djibouti")
var egypt: String = tr("Egypt")
var equatorial_guinea: String = tr("Equatorial Guinea")
var eritrea: String = tr("Eritrea")
var ethiopia: String = tr("Ethiopia")
var gabon: String = tr("Gabon")
var gambia: String = tr("Gambia")
var ghana: String = tr("Ghana")
var guinea: String = tr("Guinea")
var ivory_coast: String = tr("Ivory Coast")
var kenya: String = tr("Kenya")
var lesotho: String = tr("Lesotho")
var liberia: String = tr("Liberia")
var libya: String = tr("Libya")
var madagascar: String = tr("Madagascar")
var malawi: String = tr("Malawi")
var mali: String = tr("Mali")
var mauritania: String = tr("Mauritania")
var mauritius: String = tr("Mauritius")
var morocco: String = tr("Morocco")
var mozambique: String = tr("Mozambique")
var namibia: String = tr("Namibia")
var niger: String = tr("Niger")
var nigeria: String = tr("Nigeria")
var rwanda: String = tr("Rwanda")
var sao_tome_and_principe: String = tr("Sao Tome and Principe")
var senegal: String = tr("Senegal")
var seychelles: String = tr("Seychelles")
var sierra_leone: String = tr("Sierra Leone")
var somalia: String = tr("Somalia")
var south_africa: String = tr("South Africa")
var south_sudan: String = tr("South Sudan")
var sudan: String = tr("Sudan")
var swaziland: String = tr("Swaziland")
var tanzania: String = tr("Tanzania")
var togo: String = tr("Togo")
var tunisia: String = tr("Tunisia")
var uganda: String = tr("Uganda")
var zambia: String = tr("Zambia")
var zimbabwe: String = tr("Zimbabwe")

# asia
var afghanistan: String = tr("Afghanistan")
var bahrain: String = tr("Bahrain")
var bangladesh: String = tr("Bangladesh")
var bhutan: String = tr("Bhutan")
var brunei: String = tr("Brunei")
var burma: String = tr("Burma")
var cambodia: String = tr("Cambodia")
var china: String = tr("China")
var east_timor: String = tr("East Timor")
var india: String = tr("India")
var indonesia: String = tr("Indonesia")
var iran: String = tr("Iran")
var iraq: String = tr("Iraq")
var israel: String = tr("Israel")
var japan: String = tr("Japan")
var jordan: String = tr("Jordan")
var kazakhstan: String = tr("Kazakhstan")
var korea_north: String = tr("North Korea")
var korea_south: String = tr("South Korea")
var kuwait: String = tr("Kuwait")
var kyrgyzstan: String = tr("Kyrgyzstan")
var laos: String = tr("Laos")
var lebanon: String = tr("Lebanon")
var malaysia: String = tr("Malaysia")
var maldives: String = tr("Maldives")
var mongolia: String = tr("Mongolia")
var nepal: String = tr("Nepal")
var oman: String = tr("Oman")
var pakistan: String = tr("Pakistan")
var philippines: String = tr("Philippines")
var qatar: String = tr("Qatar")
var russian_federation: String = tr("Russian Federation")
var saudi_arabia: String = tr("Saudi Arabia")
var singapore: String = tr("Singapore")
var sri_lanka: String = tr("Sri Lanka")
var syria: String = tr("Syria")
var tajikistan: String = tr("Tajikistan")
var thailand: String = tr("Thailand")
var turkey: String = tr("Turkey")
var turkmenistan: String = tr("Turkmenistan")
var united_arab_emirates: String = tr("United Arab Emirates")
var uzbekistan: String = tr("Uzbekistan")
var vietnam: String = tr("Vietnam")
var yemen: String = tr("Yemen")


