# SPDX-FileCopyrightText: 2023 Simon Dalvai <info@simondalvai.org>

# SPDX-License-Identifier: AGPL-3.0-or-later

#
# Kind of a hack to get Godot detect continent and nation names
# so they get added to game.pot file for translations
#

class_name NationNames

# europe
var albania: String = tr("ALBANIA")
var andorra: String = tr("ANDORRA")
var armenia: String = tr("ARMENIA")
var austria: String = tr("AUSTRIA")
var azerbaijan: String = tr("AZERBAIJAN")
var belarus: String = tr("BELARUS")
var belgium: String = tr("BELGIUM")
var bosnia_and_herzegovina: String = tr("BOSNIA_AND_HERZEGOVINA")
var bulgaria: String = tr("BULGARIA")
var croatia: String = tr("CROATIA")
var cyprus: String = tr("CYPRUS")
var czech_republic: String = tr("CZECH_REPUBLIC")
var denmark: String = tr("DENMARK")
var estonia: String = tr("ESTONIA")
var finland: String = tr("FINLAND")
var france: String = tr("FRANCE")
var georgia: String = tr("GEORGIA")
var germany: String = tr("GERMANY")
var greece: String = tr("GREECE")
var hungary: String = tr("HUNGARY")
var iceland: String = tr("ICELAND")
var ireland: String = tr("IRELAND")
var italy: String = tr("ITALY")
var latvia: String = tr("LATVIA")
var liechtenstein: String = tr("LIECHTENSTEIN")
var lithuania: String = tr("LITHUANIA")
var luxembourg: String = tr("LUXEMBOURG")
var macedonia: String = tr("MACEDONIA")
var malta: String = tr("MALTA")
var moldova: String = tr("MOLDOVA")
var monaco: String = tr("MONACO")
var montenegro: String = tr("MONTENEGRO")
var netherlands: String = tr("NETHERLANDS")
var norway: String = tr("NORWAY")
var poland: String = tr("POLAND")
var portugal: String = tr("PORTUGAL")
var romania: String = tr("ROMANIA")
var san_marino: String = tr("SAN_MARINO")
var serbia: String = tr("SERBIA")
var slovakia: String = tr("SLOVAKIA")
var slovenia: String = tr("SLOVENIA")
var spain: String = tr("SPAIN")
var sweden: String = tr("SWEDEN")
var switzerland: String = tr("SWITZERLAND")
var ukraine: String = tr("UKRAINE")
var united_kingdom: String = tr("UNITED_KINGDOM")
var vatican_city: String = tr("VATICAN_CITY")

# south america
var brazil: String = tr("BRAZIL")
var argentina: String = tr("ARGENTINA")
var bolivia: String = tr("BOLIVIA")
var chile: String = tr("CHILE")
var colombia: String = tr("COLOMBIA")
var ecuador: String = tr("ECUADOR")
var guyana: String = tr("GUYANA")
var paraguay: String = tr("PARAGUAY")
var peru: String = tr("PERU")
var suriname: String = tr("SURINAME")
var uruguay: String = tr("URUGUAY")
var venezuela: String = tr("VENEZUELA")

# north america
var antigua_and_barbuda: String = tr("ANTIGUA_AND_BARBUDA")
var bahamas: String = tr("BAHAMAS")
var barbados: String = tr("BARBADOS")
var belize: String = tr("BELIZE")
var canada: String = tr("CANADA")
var costa_rica: String = tr("COSTA_RICA")
var cuba: String = tr("CUBA")
var dominica: String = tr("DOMINICA")
var dominican_republic: String = tr("DOMINICAN_REPUBLIC")
var el_salvador: String = tr("EL_SALVADOR")
var grenada: String = tr("GRENADA")
var guatemala: String = tr("GUATEMALA")
var haiti: String = tr("HAITI")
var honduras: String = tr("HONDURAS")
var jamaica: String = tr("JAMAICA")
var mexico: String = tr("MEXICO")
var nicaragua: String = tr("NICARAGUA")
var panama: String = tr("PANAMA")
var saint_kitts_and_nevis: String = tr("SAINT_KITTS_AND_NEVIS")
var saint_lucia: String = tr("SAINT_LUCIA")
var saint_vincent_and_the_grenadines: String = tr("SAINT_VINCENT_AND_THE_GRENADINES")
var trinidad_and_tobago: String = tr("TRINIDAD_AND_TOBAGO")
var usa: String = tr("USA")

# oceania
var australia: String = tr("AUSTRALIA")
var fiji: String = tr("FIJI")
var kiribati: String = tr("KIRIBATI")
var marshall_islands: String = tr("MARSHALL_ISLANDS")
var micronesia: String = tr("MICRONESIA")
var nauru: String = tr("NAURU")
var new_zealand: String = tr("NEW_ZEALAND")
var palau: String = tr("PALAU")
var papua_new_guinea: String = tr("PAPUA_NEW_GUINEA")
var samoa: String = tr("SAMOA")
var solomon_islands: String = tr("SOLOMON_ISLANDS")
var tonga: String = tr("TONGA")
var tuvalu: String = tr("TUVALU")
var vanuatu: String = tr("VANUATU")

# africa
var algeria: String = tr("ALGERIA")
var angola: String = tr("ANGOLA")
var benin: String = tr("BENIN")
var botswana: String = tr("BOTSWANA")
var burkina: String = tr("BURKINA")
var burundi: String = tr("BURUNDI")
var cameroon: String = tr("CAMEROON")
var cape_verde: String = tr("CAPE_VERDE")
var central_african_republic: String = tr("CENTRAL_AFRICAN_REPUBLIC")
var chad: String = tr("CHAD")
var comoros: String = tr("COMOROS")
var congo: String = tr("CONGO")
var democratic_republic_of_congo: String = tr("DEMOCRATIC_REPUBLIC_OF_CONGO")
var djibouti: String = tr("DJIBOUTI")
var egypt: String = tr("EGYPT")
var equatorial_guinea: String = tr("EQUATORIAL_GUINEA")
var eritrea: String = tr("ERITREA")
var ethiopia: String = tr("ETHIOPIA")
var gabon: String = tr("GABON")
var gambia: String = tr("GAMBIA")
var ghana: String = tr("GHANA")
var guinea: String = tr("GUINEA")
var ivory_coast: String = tr("IVORY_COAST")
var kenya: String = tr("KENYA")
var lesotho: String = tr("LESOTHO")
var liberia: String = tr("LIBERIA")
var libya: String = tr("LIBYA")
var madagascar: String = tr("MADAGASCAR")
var malawi: String = tr("MALAWI")
var mali: String = tr("MALI")
var mauritania: String = tr("MAURITANIA")
var mauritius: String = tr("MAURITIUS")
var morocco: String = tr("MOROCCO")
var mozambique: String = tr("MOZAMBIQUE")
var namibia: String = tr("NAMIBIA")
var niger: String = tr("NIGER")
var nigeria: String = tr("NIGERIA")
var rwanda: String = tr("RWANDA")
var sao_tome_and_principe: String = tr("SAO_TOME_AND_PRINCIPE")
var senegal: String = tr("SENEGAL")
var seychelles: String = tr("SEYCHELLES")
var sierra_leone: String = tr("SIERRA_LEONE")
var somalia: String = tr("SOMALIA")
var south_africa: String = tr("SOUTH_AFRICA")
var south_sudan: String = tr("SOUTH_SUDAN")
var sudan: String = tr("SUDAN")
var swaziland: String = tr("SWAZILAND")
var tanzania: String = tr("TANZANIA")
var togo: String = tr("TOGO")
var tunisia: String = tr("TUNISIA")
var uganda: String = tr("UGANDA")
var zambia: String = tr("ZAMBIA")
var zimbabwe: String = tr("ZIMBABWE")

# asia
var afghanistan: String = tr("AFGHANISTAN")
var bahrain: String = tr("BAHRAIN")
var bangladesh: String = tr("BANGLADESH")
var bhutan: String = tr("BHUTAN")
var brunei: String = tr("BRUNEI")
var burma: String = tr("BURMA")
var cambodia: String = tr("CAMBODIA")
var china: String = tr("CHINA")
var east_timor: String = tr("EAST_TIMOR")
var india: String = tr("INDIA")
var indonesia: String = tr("INDONESIA")
var iran: String = tr("IRAN")
var iraq: String = tr("IRAQ")
var israel: String = tr("ISRAEL")
var japan: String = tr("JAPAN")
var jordan: String = tr("JORDAN")
var kazakhstan: String = tr("KAZAKHSTAN")
var korea_north: String = tr("KOREA_NORTH")
var korea_south: String = tr("KOREA_SOUTH")
var kuwait: String = tr("KUWAIT")
var kyrgyzstan: String = tr("KYRGYZSTAN")
var laos: String = tr("LAOS")
var lebanon: String = tr("LEBANON")
var malaysia: String = tr("MALAYSIA")
var maldives: String = tr("MALDIVES")
var mongolia: String = tr("MONGOLIA")
var nepal: String = tr("NEPAL")
var oman: String = tr("OMAN")
var pakistan: String = tr("PAKISTAN")
var philippines: String = tr("PHILIPPINES")
var qatar: String = tr("QATAR")
var russian_federation: String = tr("RUSSIAN_FEDERATION")
var saudi_arabia: String = tr("SAUDI_ARABIA")
var singapore: String = tr("SINGAPORE")
var sri_lanka: String = tr("SRI_LANKA")
var syria: String = tr("SYRIA")
var tajikistan: String = tr("TAJIKISTAN")
var thailand: String = tr("THAILAND")
var turkey: String = tr("TURKEY")
var turkmenistan: String = tr("TURKMENISTAN")
var united_arab_emirates: String = tr("UNITED_ARAB_EMIRATES")
var uzbekistan: String = tr("UZBEKISTAN")
var vietnam: String = tr("VIETNAM")
var yemen: String = tr("YEMEN")


