<!--
SPDX-FileCopyrightText: 2024 Simon Dalvai <info@simondalvai.org>

SPDX-License-Identifier: CC0-1.0
-->

name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: |
          Thanks for your interest in contributing to 99 Managers Futsal Edition!

          Unfortunately, you are in the wrong place. As stated in the README, this Github repo is a read-only mirror and development happens on Codeberg: https://codeberg.org/dulvui/99managers-futsal-edition.

          Please open a pull request on Codeberg instead.
